version: '3.8'

volumes:
  pg-data:

services:
  db:
    container_name: postgres14
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"